# keys and xpaths
browser=edge
#================================================
id=//input[@id='user-name']
password=//input[@id='password']
login_btn=//input[@id='login-button']
next=//div[@class='app_logo']
product=//button[@name='add-to-cart-sauce-labs-onesie']
cart_badge=//span[@class='shopping_cart_badge']
cart_item=//span[@class='shopping_cart_badge']
quantity=//div[@class='cart_quantity']
checkout=//button[@class='btn btn_action btn_medium checkout_button ']
Chck_itm_name=//div[@class='inventory_item_name']
Chk_Unit_Price=//div[@class='inventory_item_price']
removebtn=//button[@id='remove-sauce-labs-onesie']
Usrdetail1=//input[@id='first-name']
Usrdetail2=//input[@id='last-name']
Usrdetail3=//input[@id='postal-code']
submit1=//input[@id='continue']
OrderSubmit=//button[@id='finish']